spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

server:
  port: 8083
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  application:
    name: location
